name: Godot Multi-Platform Build & Export

on:
  workflow_dispatch:
env:
  GODOT_VERSION: 4.4.1
  APP_NAME: "植物大战僵尸杂交版"
  APP_VER: "0.3"

jobs:

  # 1. 下载导出模板（示例只示范linux x86_64/arm64和iOS几个，Android可同理）
  download-export-templates:
    runs-on: ubuntu-latest
    outputs:
      linux_x86_64_artifact: export-templates-linux-x86_64.zip
      linux_arm64_artifact: export-templates-linux-arm64.zip
      ios_artifact: export-templates-ios.zip
    steps:
      - name: Download Export Template
        run: |
          wget -q https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v${{ env.GODOT_VERSION }}-stable_export_templates.tpz
          unzip Godot_v${{ env.GODOT_VERSION }}-stable_export_templates.tpz
          mv Godot_v${{ env.GODOT_VERSION }}-stable_export_templates/templates . && rm Godot_v${{ env.GODOT_VERSION }}-stable_export_templates* -rf
          pushd templates && rm windows* linux_debug* && popd
    
      - name: Upload Android artifact
        uses: actions/upload-artifact@v4
        with:
          name: export-templates
          path: templates/
                 
  # 2. 准备Godot项目工程：解压ZIP，找到PCK，使用gdsdecomp还原项目
  prepare-godot-project:
    runs-on: windows-latest
    outputs:
      godot_project_artifact: godot-project.zip
      pck_file_path: ${{ steps.find_pck.outputs.pck_path }}
      version: ${{ steps.set_version.outputs.version }}
    steps:
      - name: Download Release ZIP and Extract Version Number
        shell: pwsh
        run: |
          Write-Host "Downloading release ZIP..."
          Invoke-WebRequest -Uri https://github.com/kero990/PvZ-Hybrid-remake-mobile/releases/download/v0.3/v0.3.zip -OutFile v0.3.zip -ErrorAction Stop

          New-Item -ItemType Directory -Path extracted -Force -ErrorAction SilentlyContinue | Out-Null
          Expand-Archive -Path v0.3.zip -DestinationPath extracted -Force -ErrorAction Stop

          $extractedContentDir = Get-ChildItem -Path "extracted" -Directory | Select-Object -First 1
          if ($extractedContentDir) {
              Write-Host "Moving content from $($extractedContentDir.FullName) to extracted/..."
              Move-Item -Path "$($extractedContentDir.FullName)\*" -Destination "extracted" -Force -ErrorAction Stop
              Remove-Item -Path $extractedContentDir.FullName -Recurse -Force -ErrorAction Stop
          } else {
              Write-Host "No top-level content directory found to move."
          }

          Remove-Item -Path v0.3.zip -Force -ErrorAction SilentlyContinue
          Remove-Item -Path "extracted\*.exe" -Force -ErrorAction SilentlyContinue

          $PCK_PATH = (Get-ChildItem -Path extracted -Recurse -Filter "*.pck" | Select-Object -First 1).FullName

          if ([string]::IsNullOrEmpty($PCK_PATH)) {
              Write-Error "No .pck file found!"
              exit 1
          }

          # 将PCK_PATH中的反斜杠替换为正斜杠，以更好地兼容Godot工具
          $PCK_PATH_FOR_GDRE = $PCK_PATH -replace '\\', '/'

          Write-Host "Contents of extracted directory:"
          Get-ChildItem -Path extracted | Format-Table -AutoSize

          Write-Host "Original pck_path=$PCK_PATH"
          Write-Host "PCK_PATH_FOR_GDRE=$PCK_PATH_FOR_GDRE"

          # 将处理后的路径写入环境变量
          Add-Content -Path $env:GITHUB_ENV -Value "PCK_PATH=$PCK_PATH_FOR_GDRE"

      - name: Clone gdsdecomp for PCK decompilation
        shell: pwsh
        run: |
          Write-Host "Downloading GDRE_tools for Windows..."
          Invoke-WebRequest -Uri https://github.com/GDRETools/gdsdecomp/releases/download/v1.0.0/GDRE_tools-v1.0.0-windows.zip -OutFile GDRE_tools-v1.0.0-windows.zip -ErrorAction Stop

          New-Item -ItemType Directory -Path gdre -Force -ErrorAction SilentlyContinue | Out-Null
          Expand-Archive -Path GDRE_tools-v1.0.0-windows.zip -DestinationPath gdre -Force -ErrorAction Stop
          Remove-Item -Path GDRE_tools-v1.0.0-windows.zip -Force -ErrorAction SilentlyContinue

          # 准备命令和参数
          $command = "gdre\gdre_tools.exe"
          $arguments = @(
              "--headless",
              "--recover=`"$env:PCK_PATH`"", # 使用反引号转义双引号，确保路径作为一个参数传递
              "--output=`"pvz-project`""
          )

          Write-Host "Running $command $($arguments -join ' ')"
          
          # 核心修改：使用管道 `"" |` 提供空输入，解决"按任意键退出"
          # 2>&1 将标准错误重定向到标准输出
          # Out-String 将所有输出捕获为一个字符串
          $GDREOutput = "" | & $command $arguments 2>&1 | Out-String
          $GDREExitCode = $LASTEXITCODE

          Write-Host "--- gdre_tools.exe Output ---"
          Write-Host $GDREOutput
          Write-Host "--- End of gdre_tools.exe Output (Exit Code: $GDREExitCode) ---"

          # 检查退出代码和输出内容以判断是否为可接受的警告
          if ($GDREExitCode -ne 0) {
              # 检查是否包含特定的警告信息
              $pluginWarning1 = "WARNING: Failed to recreate plugin.cfg for AdobeAnimateEditor"
              $pluginWarning2 = "WARNING: Failed to recreate plugin.cfg for com.heroiclabs.nakama"

              if ($GDREOutput -match $pluginWarning1 -and $GDREOutput -match $pluginWarning2) {
                  Write-Warning "gdre_tools.exe exited with non-zero code ($GDREExitCode) but only detected plugin.cfg warnings. Continuing as success."
                  exit 0 # 强制成功，以便GitHub Actions继续
              } else {
                  Write-Error "gdre_tools.exe failed with unexpected errors (Exit Code: $GDREExitCode)."
                  exit $GDREExitCode # 报告真正的错误
              }
          } else {
              Write-Host "gdre_tools.exe completed successfully."
          }
          
      - name: Upload Project Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pvz-project
          path: pvz-project/
          
      - name: Upload PCK File Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pck-file
          path: "${{ env.PCK_PATH }}"

  # 3. Linux导出任务 示例只基于 linux_x86_64 模板和 pck 打包
  export-linux:
    runs-on: ubuntu-latest
    needs:
      - download-export-templates
      - prepare-godot-project
    container:
      image: debian:10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Download Export Template artifact
        uses: actions/download-artifact@v4
        with:
          name: export-templates
          path: ./export_templates

      - name: Unzip Export Template
        run: |
          sed -i.bak 's/deb.debian.org/archive.debian.org/g' /etc/apt/sources.list
          apt update && apt install unzip wget curl git make dpkg -y
          unzip ./export_templates/export-templates.zip -d ./export_templates
        
      - name: Download pck-file
        uses: actions/download-artifact@v4
        with:
          name: pck-file
          path: ./pckfile

      - name: pre deb file
        run: |
          # 打包x86_64 deb
          mkdir -p deb/DEBIAN
          mkdir -p deb/opt/apps/com.pvzhe.hybrid-remake/files
          mkdir -p deb/opt/apps/com.pvzhe.hybrid-remake/entries/applications
          mkdir -p deb/opt/apps/com.pvzhe.hybrid-remake/entries/icons/hicolor/128x128/apps
          sed -i s@VERSION@$APP_VER@G assets/control
          sed -i s@amd64@ARCH@g assets/info
          sed -i s@VERSION@$APP_VER@G assets/info
          sed -i s@amd64@ARCH@g assets/control
          chmod +x assets/run.sh
          echo './linux_release.arm64 --main-pack 植物大战僵尸杂交版v0.3发布版.pck $@' >> assets/run.sh
          PCK_PATH=$(find pckfile -name "*.pck" | head -n1)
          cp $PCK_PATH deb/opt/apps/com.pvzhe.hybrid-remake/files
          cp assets/run.sh deb/opt/apps/com.pvzhe.hybrid-remake/files
          cp ./export_templates/templates/linux_release.x86_64 deb/opt/apps/com.pvzhe.hybrid-remake/files
          cp assets/com.pvzhe.hybrid-remake.png deb/opt/apps/com.pvzhe.hybrid-remake/entries/icons/hicolor/128x128/apps
          cp assets/control deb/DEBIAN
          cp assets/com.pvzhe.hybrid-remake.desktop deb/opt/apps/com.pvzhe.hybrid-remake/entries/applications
          cp assets/info deb/opt/apps/com.pvzhe.hybrid-remake
          dpkg-deb -b deb/
          mv deb.deb com.pvzhe.hybrid-remake_0.3_amd64.deb
          
          # 打包arm64 deb
          sed -i s@arm64@amd64@g deb/opt/apps/com.pvzhe.hybrid-remake/info
          sed -i s@arm64@amd64@g deb/DEBIAN/control
          rm deb/opt/apps/com.pvzhe.hybrid-remake/files/linux_release.x86_64
          cp ./export_templates/templates/linux_release.arm64 deb/opt/apps/com.pvzhe.hybrid-remake/files
          sed -i s@x86_64@arm64@g deb/opt/apps/com.pvzhe.hybrid-remake/files/run.sh
          dpkg-deb -b deb/
          mv deb.deb com.pvzhe.hybrid-remake_0.3_arm64.deb
          
      - name: Upload Linux build to Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./*.deb # 指定要上传的文件
          tag_name: v$APP_VER 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
        
  # 4. Android 导出任务 示例，使用反编译工程，需根据实际环境配置签名等参数
  export-android:
    runs-on: ubuntu-latest
    needs:
      - download-export-templates
      - prepare-godot-project
    steps:
      - name: Setup Java & Android SDK
        uses: android-actions/setup-android@v2

      - name: Download Export Templates Android (示例需要添加相应下载Job)
        uses: actions/download-artifact@v4
        with:
          name: export-templates
          path: ./export_template

      - name: Download Godot project artifact
        uses: actions/download-artifact@v4
        with:
          name: godot-project
          path: ./godot_project.zip

      - name: Unzip Godot project
        run: unzip pvz_project.zip -d ./pvz_project
        
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Godot Android Export
        run: |
          wget -q https://github.com/godotengine/godot/releases/download/$GODOT_VERSION-stable/Godot_v$GODOT_VERSION-stable_linux.x86_64.zip
          unzip Godot_v$GODOT_VERSION-stable_linux.x86_64.zip -d godot
          chmod +x godot/Godot_v$GODOT_VERSION-stable_linux.x86_64
          cp assets/android/export_presets.cfg godot_project
          godot/Godot_v$GODOT_VERSION-stable_linux.x86_64 --path ./godot_project --export "Android" exported.apk

      - name: Upload Android artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: exported.apk


  # 5. iOS 导出任务 示例，同样使用完整Godot项目
  export-ios:
    runs-on: macos-latest
    needs:
      - download-export-templates
      - prepare-godot-project
    steps:
      - name: Download Export Templates iOS artifact
        uses: actions/download-artifact@v4
        with:
          name: export-templates
          path: ./export_template

      - name: Unzip Export Template
        run: unzip ./export_templates_ios/export-templates.zip -d ./export_templates

      - name: Download Godot project artifact
        uses: actions/download-artifact@v4
        with:
          name: godot-project
          path: ./godot_project.zip

      - name: Unzip Godot project
        run: unzip godot_project.zip -d ./godot_project

      - name: Setup Godot iOS Export (请根据实际需求调整)
        uses: dulvui/godot4-ios-export@v1
        with:
          godot-version: ${{ env.GODOT_VERSION }}

      - name: Godot iOS Export
        run: godot --path ./godot_project --export "iOS" exported.xcodeproj

      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: exported.xcodeproj

  # 6. macOS 导出任务 示例，直接模板+PCK方式打包
  export-macos:
    runs-on: macos-latest
    needs:
      - download-export-templates
      - prepare-godot-project
    steps:
      - name: Download MacOS Export Template artifact
        uses: actions/download-artifact@v4
        with:
          name: export-templates
          path: ./export_templates

      - name: Unzip MacOS Export Template
        run: unzip ./export_templates_macos/export-templates.zip -d ./export_templates

      - name: Copy executable and PCK
        run: |
          cp ./export_templates/export_templates/macos_release "./${{ env.APP_NAME }}.app"
          cp ${{ needs.prepare-godot-project.outputs.pck_file_path }} .

      - name: Zip macOS package
        run: zip -r "${{ env.APP_NAME }}_macos_${{ needs.prepare-godot-project.outputs.version }}.zip" "${{ env.APP_NAME }}.app" *.pck

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: ${{ env.APP_NAME }}_macos_*.zip
